### ISSUE TITLE
Install fail when using docker haskell

### ISSUE THREAD

**Issue by ledongthuc** [kallisti-dev/hs-webdriver#100] opened 2016-09-03 18:25 UTC
Not sure it's duplicated or not. When I try to install the library in Docker haskell ( https://hub.docker.com/_/haskell/ ) with command

`cabal update; cabal install webdriver;`

I got the error message:

```
src/Test/WebDriver/Internal.hs:16:82: error:
    Module
    ‘Network.HTTP.Client’
    does not export
    ‘HttpException(ResponseTimeout)’
cabal: Leaving directory '/tmp/cabal-tmp-59/webdriver-0.8.3'
cabal: Error: some packages failed to install:
webdriver-0.8.3 failed during the building phase. The exception was:
ExitFailure 1
```

When install with stack, It installed successfully (not sure about run)

**Comment by kallisti-dev** [comment] 2016-09-28 18:53
I believe this is a duplicate of #98. The next webdriver release will have a fix for that issue. If you still have problems in the Docker environment after the update, please let me know.

**Comment by kallisti-dev** [comment] 2016-09-30 15:33
I've closed #98, but leaving this issue open until we confirm that it's a duplicate.

**Comment by kallisti-dev** [comment] 2016-10-03 14:06
[0.8.4](https://hackage.haskell.org/package/webdriver-0.8.4) has been released. Let me know if this new version resolves the issue for you.

**Comment by ledongthuc** [comment] 2016-10-04 22:28
@kallisti-dev: It works well, thanks.

**Comment by kallisti-dev** [comment] 2016-10-05 14:19
Yeah that's some issue with cabal's build plan selecting the older version. Thanks for reporting.

**Closed by kallisti-dev** 2016-10-05 14:19 UTC
Labels: dependency, duplicate
